PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE d1_migrations(
		id         INTEGER PRIMARY KEY AUTOINCREMENT,
		name       TEXT UNIQUE,
		applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO d1_migrations VALUES(1,'0001_create_user_table.sql','2024-04-22 11:54:05');
CREATE TABLE IF NOT EXISTS "A" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "bId" INTEGER NOT NULL,
    CONSTRAINT "A_bId_fkey" FOREIGN KEY ("bId") REFERENCES "B" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO A VALUES(1,1);
CREATE TABLE IF NOT EXISTS "B" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);
INSERT INTO B VALUES(1);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('B',1);
INSERT INTO sqlite_sequence VALUES('A',1);
INSERT INTO sqlite_sequence VALUES('d1_migrations',1);
