#:schema node_modules/wrangler/config-schema.json
name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "export-order-issue-db-1"
database_id = "e4e46daf-504d-447d-ab29-979c13a9cabb"